Repository Azure/terraform-azurerm-avm-res-machinelearningservices-workspace, pull requests merged in 2024-09, with the labels that each got.

#53 Networking clean up & Private AI Studio changes
  README.md
  examples/private_ai_studio/README.md
  examples/private_ai_studio/_header.md
  examples/private_ai_studio/main.tf
  examples/private_ai_studio/variables.tf
  main.cognitiveservices.tf
  main.containerregistry.tf
  main.keyvault.tf
  main.storage.tf
  variables.tf
Labels: Needs: Triage :mag:, Language: Terraform :globe_with_meridians:

#58 Making version dependent on gratar than instead of fixed
  README.md
  terraform.tf
Labels: Needs: Triage :mag:

#63 Adding additional private endpoints
  README.md
  locals.tf
  main.tf
  variables.tf
Labels: Needs: Triage :mag:

#67 Standard naming should also apply to passed in variables.
  locals.tf
Labels: bug, Needs: Triage :mag:, Language: Terraform :globe_with_meridians:
